### ISSUE TITLE
Unable to checkout HEAD

### ISSUE THREAD

**Issue by meenakshi-dhanani** [poush/LatexGo#11]
<img width="1440" alt="Screen Shot 2020-03-29 at 9 36 13 PM" src="https://user-images.githubusercontent.com/14279061/77854127-f344d980-7205-11ea-9986-644861b65609.png">

```
Error downloading object: texlivejs/texlive/LICENSE.CTAN
fatal: texlivejs/texlive/LICENSE.CTAN: smudge filter lfs failed
```

I would like to contribute to a good first issue, but getting stuck at this point. 
Please help solve this issue

**Comment by poush** [comment]
Thanks @meenakshi-dhanani to report it. We were aware of it and fixed it now so you can take the fresh clone and it should work.

**Comment by meenakshi-dhanani** [comment]
Works for me now, thank you

**Comment by meenakshi-dhanani** [comment]
Works for me now, thank you
