### ISSUE TITLE
Add: Dialogflow agent to use voice over snippets

### ISSUE THREAD

**Issue by poush** [poush/LatexGo#5]

**Comment by sakshichahal53** [comment]
Hi @poush, I have already worked on DialogFlow and would like to contribute to this issue. However, could you please help in the kickstart and provide a detailed description of the project?

**Comment by poush** [comment]
Hi @sakshichahal53, I understand it has been quite long since you expressed the interest and apologies for late reply but I think it would be better to keep this for future. For this reason, I'm closing the issue.
In case you are still interested, we are again participating in RGSoC this year and have so many ideas to work on. And if you are specifically interested in Dialogflow or voice integration then I think It might be more suitable for the [H2 project](https://github.com/h2org/h2). Thanks!
